"""Первая миграция

Revision ID: 2c7739149279
Revises: 
Create Date: 2026-07-05 16:36:28.248198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c7739149279'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Parent_Products',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('parent_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('parent_id')
    )
    op.create_index(op.f('ix_Parent_Products_parent_id'), 'Parent_Products', ['parent_id'], unique=False)
    op.create_table('Users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_Users_user_id'), 'Users', ['user_id'], unique=False)
    op.create_table('Variants',
    sa.Column('var_id', sa.Integer(), nullable=False),
    sa.Column('var_name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('var_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['Parent_Products.parent_id'], ),
    sa.PrimaryKeyConstraint('var_id')
    )
    op.create_index(op.f('ix_Variants_parent_id'), 'Variants', ['parent_id'], unique=False)
    op.create_index(op.f('ix_Variants_var_id'), 'Variants', ['var_id'], unique=False)
    op.create_table('Stocks',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('var_id', sa.Integer(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['var_id'], ['Variants.var_id'], ),
    sa.PrimaryKeyConstraint('stock_id')
    )
    op.create_index(op.f('ix_Stocks_stock_id'), 'Stocks', ['stock_id'], unique=False)
    op.create_index(op.f('ix_Stocks_var_id'), 'Stocks', ['var_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Stocks_var_id'), table_name='Stocks')
    op.drop_index(op.f('ix_Stocks_stock_id'), table_name='Stocks')
    op.drop_table('Stocks')
    op.drop_index(op.f('ix_Variants_var_id'), table_name='Variants')
    op.drop_index(op.f('ix_Variants_parent_id'), table_name='Variants')
    op.drop_table('Variants')
    op.drop_index(op.f('ix_Users_user_id'), table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_Parent_Products_parent_id'), table_name='Parent_Products')
    op.drop_table('Parent_Products')
    # ### end Alembic commands ###
