"""Created Index

Revision ID: 95fe882ebbd9
Revises: abd03af17549
Create Date: 2026-08-08 18:42:10.261366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95fe882ebbd9'
down_revision: Union[str, Sequence[str], None] = 'abd03af17549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.drop_index(op.f('ix_Stocks_stock_id'), table_name='Stocks')
    op.drop_index(op.f('ix_Stocks_var_id'), table_name='Stocks')
    op.drop_table('Stocks')
    op.drop_index(op.f('ix_Parent_Products_parent_id'), table_name='Parent_Products')
    op.create_index('ix_product_parent_name', 'Parent_Products', ['parent_name'], unique=False, postgresql_using='gin', postgresql_ops={'parent_name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_Users_user_id'), table_name='Users')
    op.add_column('Variants', sa.Column('var_quantity', sa.Integer(), nullable=False, server_default = '0'))
    op.alter_column('Variants', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Variants', 'var_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_index(op.f('ix_Variants_var_id'), table_name='Variants')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Variants_var_id'), 'Variants', ['var_id'], unique=False)
    op.alter_column('Variants', 'var_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('Variants', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('Variants', 'var_quantity')
    op.create_index(op.f('ix_Users_user_id'), 'Users', ['user_id'], unique=False)
    op.drop_index('ix_product_parent_name', table_name='Parent_Products', postgresql_using='gin', postgresql_ops={'parent_name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_Parent_Products_parent_id'), 'Parent_Products', ['parent_id'], unique=False)
    op.create_table('Stocks',
    sa.Column('stock_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('var_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stock_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['var_id'], ['Variants.var_id'], name=op.f('Stocks_var_id_fkey')),
    sa.PrimaryKeyConstraint('stock_id', name=op.f('Stocks_pkey'))
    )
    op.create_index(op.f('ix_Stocks_var_id'), 'Stocks', ['var_id'], unique=False)
    op.create_index(op.f('ix_Stocks_stock_id'), 'Stocks', ['stock_id'], unique=False)
    op.execute("DROP EXTENSION IF EXISTS pg_trgm;")
    # ### end Alembic commands ###
