"""First change of tables

Revision ID: abd03af17549
Revises: 4341b16489e9
Create Date: 2026-07-18 18:57:06.630728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd03af17549'
down_revision: Union[str, Sequence[str], None] = '4341b16489e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Parent_Products', ['parent_name'])
    op.create_unique_constraint('var_name_parent_id', 'Variants', ['parent_id', 'var_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('var_name_parent_id', 'Variants', type_='unique')
    op.drop_constraint(None, 'Parent_Products', type_='unique')
    # ### end Alembic commands ###
